[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aimdo"
version = "0.0.1"

[tool.setuptools.package-data]
"aimdo" = ["*.so", "*.dll"]
