name: Build Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build custom build image
        if: runner.os == 'Linux'
        run: docker build -t custom-cuda-builder -f docker/cuda-on-manylinux.Dockerfile .

      - name: Install CUDA (Windows)
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.1.1' # Just for headers/libs; binary remains compatible back to 11.x
          use-github-cache: false
          use-local-cache: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: custom-cuda-builder 
          CIBW_BUILD: "cp3*-manylinux_x86_64 cp3*-win_amd64"
          CIBW_SKIP: "cp3[0-8]-*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --exclude libcuda.so.1 -w {dest_dir} {wheel}"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
